version: '3'
services:
  backend:
    image: alfonzso/chdiary-be:htmx.v0.0.3
    build:
      context: .
      dockerfile: Dockerfile
      args:
          PRISMA_ENV: local
    volumes:
      - .env:/home/node/app/.env
      - ./prisma.local:/home/node/app/prisma.local
    ports:
      - "8890:8888"

  frontend:
    image: alfonzso/chdiary-fe:htmx.v0.0.1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8889:80"
