version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
          PRISMA_ENV: local
    volumes:
      - .env:/home/node/app/.env
      - ./prisma.local:/home/node/app/prisma.local
    ports:
      - "8890:8888"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8889:80"
