export let foodNamesList = [
  "Áfonyás fahéjas banánleves, Sertéskaraj fitt magvas panírban, gombás-cukkinis rizs",
  "Baconba tekert csirkemell gombás tojásos rizzsel",
  "Bakonyi sertésszelet, tészta köret",
  "Bangkoki marha (távol-keleti szósz, tészta, marhahús)",
  "Bordói marharagu tésztaágyon",
  "Borsos tokány, főtt burgonya",
  "Brokkolival töltött csirke, zöldségekkel",
  "Cordon bleu pulykamell, párolt zöldekkel (c.bab, bébi répa, lila hagyma)",
  "Csípős chilis csirkecomb, gombás-cukkinis rizs",
  "Csípős chilis pácolt csirkecomb filé zabpelyhes panírban, vajon párolt zöldségmix",
  "Csirkefalatok thai módra (csirkecomb, chili, fitt tészta, paradicsom)",
  "Csirkemell Holstein módra, zöldségekkel, rizzsel",
  "Csirkemell orly módon, párolt burgonyával zöldekkel, petrezselyemmel",
  "Csirkemell sajtos bundában, zöldséges barnarizs",
  "Csontleves friss zöldséggekkel cérnametélttel, Fitt milánói sertés borda",
  "Diós bundában sült csirkefalatok, Amerikai káposztasaláta",
  "Dubarry pulykamell, basmati rizses zöldség",
  "Fitt májgaluska leves, Diós bundában sült csirkefalatok, Amerikai káposztasaláta",
  "Fitt májgaluska leves, Rántott fűszeres csirkecomb, petrezselymes burg., grill zöldségekkel",
  "Fitt májgaluska leves, Rántott sertésborda, sült zöldség (light)",
  "Fitt rántott csirkecomb filé, tojásos franciasaláta",
  "Fitt rántott csirkecomb filé, vajban párolt zöldekkel, barnarizzsel",
  "Friss citromos barack krémleves, Óvári sertésborda, tepsis burgonyával, bébi répával",
  "Füstölt sajttal, gombával töltött rántott csirkemell, jázmin rizs",
  "Gombapaprikás, szarvacska tészta V",
  "Gyros pitában zöldsalátával",
  "Gyros tál (csirke, burgonya, saláta, joghurt)",
  "Házi lecsó virslivel, bulgurral",
  "Házi lecsó, virslivel, hajdinával",
  "Húsleves sovány pulykamellből, Mátrai borzas csirkemell, rizses zöldség",
  "Húsos rakott karfiol (pulykahússal)",
  "Joghurtos csirkemell, sült gombával, basmati rizzsel",
  "Juhtúrós burgonya tepsiben sütve V",
  "Juhtúróval töltött rántott csirkemell, wok zöldségekkel",
  "Kemencében sült csirkemell cheddar sajt mártással, párolt zöldségköret",
  "Kemencében sült csirkemell csíkozva, párolt zöldségköret",
  "Kemencés csirkemellcsíkok cheddar sajttal, bulgur salátával",
  "Kentucky csirkecomb, tojásos franciasaláta",
  "Könnyű tejfölös zöldbableves, Fűszeres mustáros roston csirkemellfilé görög saláta",
  "Könnyű túrós csusza V",
  "Könnyű zöldséges zöldborsóleves, Töltött paprika csirkemellből",
  "Lecsó virslivel, rizzsel",
  "Light tejfölös lencseleves zöldségekkel, Fitt rakott zöldbab (csirkemellel, tejföllel)",
  "Magyaros zöldbabfőzelék, sokmagvas zöldségfasírt V",
  "Májgaluska leves gazdagon zöldségekkel, Rántott gomba, burgonyapüré (light)",
  "Marhahúsleves zöldségekkel gazdagon, Fitt tejfölös burgonyafőzelék, vaslapon sült csirkefalatok",
  "Marhapörkölt főtt burgonyával",
  "Marokkói vöröslencsekrém leves, Fitt rakott karfiol pulykahússal",
  "Mátrai borzas csirkemell, rizses zöldség",
  "Mátrai borzas csirkemell, sült zöldségek",
  "Mézes-chilis csirkecomb, párolt zöldségek",
  "Mozzarellás csirkemell pitában",
  "Mozzarellás sült csirkemell tekercs, vajas bébirépa",
  "Négy sajttal töltött csirkemell zabpelyhes panírban, rizses zöldség",
  "Olasz paradicsomleves (bazsalikom, tejszín), Tojásos fitt lecsó kolbásszal, burgurral",
  "Olaszos tepsis csirkemell, zöldséges vadrizs",
  "Óvári sertésborda, tepsis burgonyával, bébi répával",
  "Pácolt sajtos csirkemell, tortilla tekercsben tejföllel zöldségekkel",
  "Pácolt, sajtos csirkecsíkok wok zöldséggel",
  "Paprikás burgonya (virslivel)",
  "Paradicsomos burgonyafőzelék,szárnyas vagdalttal",
  "Párizsi pulykamell, csőben sült karfiol",
  "Pirított csirkecsíkok zöldsalátával tepsis burgonyával",
  "Pirított sertésmáj, főtt burgonya",
  "Póréhagymás sárgarépás gombaleves, Roston csirkemell, négysajtmártás, párolt karotta borsóval, kukoricával",
  "Rakott karfiol pulykahússal és zabpehellyel",
  "Rántott csirkemell fitt sajtos panírban, sült zöldség",
  "Rántott fűszeres csirkecomb, amerikai káposztasaláta",
  "Rántott fűszeres csirkecomb, petrezselymes burg., grill zöldségekkel",
  "Rántott sertésborda, sült zöldség (light)",
  "Roston csirkemell, négysajtmártás, párolt karotta borsóval, kukoricával",
  "Roston sült csirkemell, zöldséges barnarizs",
  "Rozmaringos csirkemell, sajtmártás, vajas bébirépa",
  "Sajtkrémmel göngyölt csirkemell, fűszeres, hagymás, sült karottával",
  "Sajtos csirkemell párolt zöldséggel (brokkoli, kukorica, cukkíni, sárgarépa)",
  "Sajtos grillezett sonka brokkolival, főtt burgonyával",
  "Sajttal, sonkával rakott karaj, zöldséges basmati rizs",
  "Sertéskaraj fitt magvas panírban, gombás-cukkinis rizs",
  "Sokmagvas rántott pulykamell, párolt burgonyával, zöldségekkel",
  "Sokmagvas rántott pulykamell, tojásos barnarizs",
  "Sonkával, gombával töltött fitt rántott palacsinta, light majonéz",
  "Szűzérmék párizsiasan, petrezselymes burgonyával, grill zöldségekkel",
  "Tárkonyos zöldségragu leves (gomba, z.borsó, zeller, gyökér), Olaszos tepsis csirkemell, zöldséges vadrizs",
  "Tavaszi zöldborsóleves, Csirkemell vadasan, szarvacska tészta",
  "Tavaszi zöldborsóleves, Sokmagvas rántott pulykamell, párolt burgonyával, zöldségekkel",
  "Tejfölös gombaleves, Lyoni marhapecsenye (sült hagymával), párolt zöldségköret",
  "Tejszínes brokkoli krémleves, Juhtúróval töltött rántott csirkemell, wok zöldségekkel",
  "Tejszínes eperleves, Rántott fűszeres csirkecomb, petrezselymes burg., grill zöldségekkel",
  "Tejszínes eperleves, Vöröslencse főzelék, light csirkemell pörkölt",
  "Tejszínes feketeszeder leves, Borjúpaprikás bulgurral",
  "Tejszínes spárgakrémleves, Sáfrányos csirkés bulgur cheddarsajttal",
  "Tejszínes zöldbabfőzlék, rántott csirkemell",
  "Tejszínes-gombás csirkemell, fitt spagetti",
  "Thai pirított marha csíkok, tojásos barnarizs",
  "Töltött paprika csirkemellből",
  "Töltött paprika pulykahúsból, zabpehellyel",
  "Töltött paprika, sós burgonya (csirkemellből)",
  "Újházy tyúkhúsleves, Bácskai csirkés bulgur",
  "Vadas marhatokány (light) spagetti",
  "Vaslapon sült csirkemell, sárgarépás barnarizs",
  "Vaslapon sült csirkemellfilé, gombás, tojásos rizs",
  "Zöldfűszeres sült csirkemell, wok zöldségkeverék",
  "Zöldfűszeres túróval göngyölt csirke, joghurtos bulgursalátával",
  "Zöldséges rizseshús",
  "Zöldséggel töltött csirkemell, joghurtos bulgursalátával",
]