name: ChDiary BE docker build

on:
  workflow_dispatch:
    inputs:
      msg:
        required: false
        description: "Manual release creation"
  #       default: "Manual push ?!"
  #     tag:
  #       required: false
  #       description: "Tag of image"
  #       default: "release-0.0"
  push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  release:
    types: # This configuration does not affect the page_build event above
      - published

jobs:

  build:
    if: |
      contains(github.event.head_commit.message, 'create-release') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@master
    #   with:
    #     platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag alfonzso/py-xlate:release-1.0.${{ github.run_number }}

    - name: Set the value
      # id: step_one
      run: |
        echo "GIT_VERSION=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
        echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | tr / - )" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        # platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        # tags: alfonzso/chdiary-be:${{ github.event.inputs.tag }}.${{ github.run_number }}
        tags: alfonzso/chdiary-be:${{ env.GIT_BRANCH }}.${{ github.run_number }}
        cache-from: type=registry,ref=alfonzso/chdiary-be:buildcache
        cache-to: type=registry,ref=alfonzso/chdiary-be:buildcache,mode=max
        build-args: |
          GIT_VERSION=${{ env.GIT_VERSION }}

    # - name: Build
    #   uses: docker/build-push-action@v2
    #   with:
    #     builder: ${{ steps.buildx.outputs.name }}
    #     context: .
    #     file: ./Dockerfile
    #     platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
    #     push: true
    #     tags: ${{ steps.prep.outputs.tags }}
